title: 
author: GitHub User 
email: 
description: > # this means to ignore newlines until "baseurl:"
  First blog ever
theme:minima
# social links
twitter_username: user # DO NOT include the @ character, or else the build will fail!
github_username:  user # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
